import pandas as pd
from sqlalchemy import create_engine

publication_data = [
    {
        "publicationTypeId": 2,
        "publicationTypeGroupId": 2,
        "publicationTypeDescription": "Global",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 564,
        "description": "Global Guide, 2022",
    },
    {
        "publicationTypeId": 5,
        "publicationTypeGroupId": 5,
        "publicationTypeDescription": "USA",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 557,
        "description": "USA Guide, 2022",
    },
    {
        "publicationTypeId": 1,
        "publicationTypeGroupId": 1,
        "publicationTypeDescription": "UK",
        "isLocationBased": False,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 556,
        "description": "UK Guide, 2022",
    },
    {
        "publicationTypeId": 14,
        "publicationTypeGroupId": 14,
        "publicationTypeDescription": "UK Bar",
        "isLocationBased": False,
        "isBarrister": True,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 559,
        "description": "UK Bar, 2022",
    },
    {
        "publicationTypeId": 7,
        "publicationTypeGroupId": 7,
        "publicationTypeDescription": "Europe",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 562,
        "description": "Chambers Europe 2022",
    },
    {
        "publicationTypeId": 8,
        "publicationTypeGroupId": 8,
        "publicationTypeDescription": "Asia-Pacific",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 563,
        "description": "Asia-Pacific 2022",
    },
    {
        "publicationTypeId": 116,
        "publicationTypeGroupId": 116,
        "publicationTypeDescription": "Greater China Region",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 829,
        "description": "Greater China Region 2022",
    },
    {
        "publicationTypeId": 9,
        "publicationTypeGroupId": 9,
        "publicationTypeDescription": "Latin America",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 560,
        "description": "Latin America Guide, 2022",
    },
    {
        "publicationTypeId": 20,
        "publicationTypeGroupId": 20,
        "publicationTypeDescription": "Canada",
        "isLocationBased": False,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 561,
        "description": "Canada Guide 2022",
    },
    {
        "publicationTypeId": 21,
        "publicationTypeGroupId": 21,
        "publicationTypeDescription": "High Net Worth",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2021,
        "isRanked": False,
        "id": 558,
        "description": "Chambers HNW 2021",
    },
    {
        "publicationTypeId": 49,
        "publicationTypeGroupId": 49,
        "publicationTypeDescription": "FinTech",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": True,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 567,
        "description": "PA: FinTech 2022",
    },
    {
        "publicationTypeId": 58,
        "publicationTypeGroupId": 58,
        "publicationTypeDescription": "Litigation Support",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": True,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 839,
        "description": "PA: Litigation Support 2022",
    },
    {
        "publicationTypeId": 77,
        "publicationTypeGroupId": 77,
        "publicationTypeDescription": "GC Influencers",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2019,
        "isRanked": False,
        "id": 405,
        "description": "GC Influencers 2019",
    },
    {
        "publicationTypeId": 94,
        "publicationTypeGroupId": 94,
        "publicationTypeDescription": "Alternative Legal Service Providers",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 840,
        "description": "PA: Alternative Legal Service Providers 2022",
    },
    {
        "publicationTypeId": 99,
        "publicationTypeGroupId": 95,
        "publicationTypeDescription": "Brazil: Contentious",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 800,
        "description": "Chambers Brazil: Contentious, 2022",
    },
    {
        "publicationTypeId": 101,
        "publicationTypeGroupId": 95,
        "publicationTypeDescription": "Brazil: Industries & Sectors",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 818,
        "description": "Chambers Brazil: Industries & Sectors, 2022",
    },
    {
        "publicationTypeId": 102,
        "publicationTypeGroupId": 95,
        "publicationTypeDescription": "Brazil: Regions",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 821,
        "description": "Chambers Brazil: Regions, 2022",
    },
    {
        "publicationTypeId": 100,
        "publicationTypeGroupId": 95,
        "publicationTypeDescription": "Brazil: Transactional",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2021,
        "isRanked": False,
        "id": 595,
        "description": "Chambers Brazil: Transactional, 2021",
    },
    {
        "publicationTypeId": 108,
        "publicationTypeGroupId": 96,
        "publicationTypeDescription": "Crisis & Risk Management",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 841,
        "description": "PA: Crisis & Risk Management 2022",
    },
    {
        "publicationTypeId": 74,
        "publicationTypeGroupId": 97,
        "publicationTypeDescription": "Law Tech",
        "isLocationBased": True,
        "isBarrister": False,
        "isProfessionalAdviser": False,
        "isDisabled": False,
        "isMostRelevant": False,
        "active": True,
        "issueOrYear": 2022,
        "isRanked": False,
        "id": 842,
        "description": "PA: LawTech 2022",
    },
]

# turn this into a table using pandas


# Example Python program to serialize a pandas DataFrame

# into a PostgreSQL table


df = pd.DataFrame(data=publication_data)

alchemyEngine = create_engine("postgresql://priyaghose:password@localhost:5432/lockwood")

postgreSQLConnection = alchemyEngine.connect()

postgreSQLTable = "PublicationTypes"


try:

    frame = df.to_sql(postgreSQLTable, postgreSQLConnection, if_exists="fail")

except ValueError as vx:

    print(vx)

except Exception as ex:

    print(ex)

else:

    print("PostgreSQL Table %s has been created successfully." % postgreSQLTable)

finally:

    postgreSQLConnection.close()
